version: "3.9"
services:
  notebooks:
    image: "jupyter/datascience-notebook:latest"
    container_name: juliaRbuddies
    user: root
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/home/jovyan/work